"""Register production-machine and machine-tool assets as catalog candidates."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];CATALOG=ROOT/"assets"/"catalog"/"candidates.catalog.json"
# slug: id, display name, category, bounds [width, height, depth], axes, signals
SPECS={
"hydraulic_c_frame_press":("machines.forming.press.hydraulic-c-frame.v1","Hydraulic C-Frame Press","machines/forming/presses",[1.7,2.5,1.3],[("ram_position","linear","KIN_PRESS_RAM",0,.55,"m",.20)],[("cycle_start","bool","input",None,None),("ram_extend","bool","input",None,"ram_position"),("ram_position","float32","output","mm",None),("pressure","float32","output","bar",None),("guard_clear","bool","output",None,None),("press_fault","bool","output",None,None)]),
"mechanical_gap_frame_press":("machines.forming.press.mechanical-gap-frame.v1","Mechanical Gap-Frame Press","machines/forming/presses",[1.9,2.5,1.4],[("flywheel_rotation","continuous","KIN_FLYWHEEL",0,360,"deg",420),("slide_position","linear","KIN_SLIDE",0,.35,"m",.25)],[("motor_run","bool","input",None,"flywheel_rotation"),("single_stroke","bool","input",None,"slide_position"),("top_of_stroke","bool","output",None,None),("bottom_of_stroke","bool","output",None,None),("press_fault","bool","output",None,None)]),
"cnc_press_brake":("machines.forming.press-brake.cnc-hydraulic.v1","CNC Hydraulic Press Brake","machines/forming/press-brakes",[3.5,2.3,1.7],[("beam_position","linear","KIN_PRESS_BEAM",0,.32,"m",.12)],[("cycle_start","bool","input",None,None),("beam_down","bool","input",None,"beam_position"),("bend_angle_setpoint","float32","input","deg",None),("beam_position","float32","output","mm",None),("safety_clear","bool","output",None,None),("machine_fault","bool","output",None,None)]),
"horizontal_bandsaw":("machines.cutting.saw.horizontal-band.v1","Horizontal Pivot Bandsaw","machines/cutting/saws",[2.8,2.2,1.3],[("bow_angle","rotary","KIN_SAW_BOW",0,45,"deg",12),("vise_position","linear","KIN_VISE_MOVING",0,.35,"m",.10)],[("cycle_start","bool","input",None,None),("saw_run","bool","input",None,None),("bow_down","bool","input",None,"bow_angle"),("vise_clamp","bool","input",None,"vise_position"),("cut_complete","bool","output",None,None),("saw_fault","bool","output",None,None)]),
"cold_saw":("machines.cutting.saw.circular-cold.v1","Pivoting Circular Cold Saw","machines/cutting/saws",[1.9,2.3,1.4],[("blade_rotation","continuous","KIN_SAW_BLADE",0,360,"deg",1800),("head_angle","rotary","KIN_SAW_HEAD_ARM",0,55,"deg",18)],[("blade_run","bool","input",None,"blade_rotation"),("head_down","bool","input",None,"head_angle"),("vise_clamped","bool","output",None,None),("cut_complete","bool","output",None,None)]),
"pedestal_grinder":("machines.finishing.grinder.double-ended-pedestal.v1","Double-Ended Pedestal Grinder","machines/finishing/grinders",[1.8,2.0,1.1],[("motor_rotation","continuous","KIN_GRINDER_MOTOR",0,360,"deg",3600)],[("run_command","bool","input",None,"motor_rotation"),("running","bool","output",None,None),("grinder_fault","bool","output",None,None)]),
"manual_engine_lathe":("machines.machining.lathe.manual-engine.v1","Manual Engine Lathe","machines/machining/lathes",[3.3,1.9,1.4],[("spindle_rotation","continuous","KIN_SPINDLE_CHUCK",0,360,"deg",2400),("carriage_position","linear","KIN_CARRIAGE",0,1.55,"m",.18)],[("spindle_run","bool","input",None,"spindle_rotation"),("spindle_speed","float32","input","rpm",None),("carriage_feed","bool","input",None,"carriage_position"),("chuck_guard_closed","bool","output",None,None),("lathe_fault","bool","output",None,None)]),
"vertical_knee_mill":("machines.machining.mill.vertical-knee.v1","Vertical Knee Milling Machine","machines/machining/mills",[1.9,2.9,1.8],[("spindle_rotation","continuous","KIN_SPINDLE",0,360,"deg",3600),("table_x","linear","KIN_X_TABLE",0,1.10,"m",.12)],[("spindle_run","bool","input",None,"spindle_rotation"),("spindle_speed","float32","input","rpm",None),("table_feed","bool","input",None,"table_x"),("mill_fault","bool","output",None,None)]),
"injection_molding_machine":("machines.plastics.injection-molder.horizontal.v1","Horizontal Injection Molding Machine","machines/plastics/injection-molding",[4.4,2.7,1.7],[("clamp_position","linear","KIN_MOVING_PLATEN",0,1.05,"m",.35),("screw_rotation","continuous","KIN_INJECTION_SCREW",0,360,"deg",360)],[("cycle_start","bool","input",None,None),("clamp_close","bool","input",None,"clamp_position"),("screw_run","bool","input",None,"screw_rotation"),("barrel_temperature","float32","output","degC",None),("clamp_closed","bool","output",None,None),("cycle_complete","bool","output",None,None),("machine_fault","bool","output",None,None)]),
"welding_positioner":("machines.welding.positioner.tilt-rotate.v1","Tilt-Rotate Welding Positioner","machines/welding/positioners",[1.8,1.8,1.7],[("table_rotation","continuous","KIN_ROTARY_TABLE",0,360,"deg",30),("table_tilt","rotary","KIN_TILT_TRUNNION",0,135,"deg",20)],[("rotate_command","bool","input",None,"table_rotation"),("rotation_speed","float32","input","rpm",None),("tilt_setpoint","float32","input","deg","table_tilt"),("positioner_fault","bool","output",None,None)]),
"resistance_spot_welder":("machines.welding.resistance.pedestal-spot.v1","Pedestal Resistance Spot Welder","machines/welding/resistance",[1.9,2.4,1.6],[("electrode_position","linear","KIN_UPPER_ELECTRODE",0,.32,"m",.18)],[("weld_trigger","bool","input",None,None),("electrode_close","bool","input",None,"electrode_position"),("weld_current","float32","output","kA",None),("weld_complete","bool","output",None,None),("welder_fault","bool","output",None,None)]),
"aqueous_parts_washer":("machines.cleaning.parts-washer.front-load-aqueous.v1","Front-Load Aqueous Parts Washer","machines/cleaning/parts-washers",[1.9,2.1,1.6],[("door_angle","rotary","KIN_FRONT_DOOR",0,105,"deg",30),("basket_rotation","continuous","KIN_WASH_BASKET",0,360,"deg",18)],[("cycle_start","bool","input",None,None),("door_open","bool","input",None,"door_angle"),("wash_pump_run","bool","input",None,None),("basket_run","bool","input",None,"basket_rotation"),("door_closed","bool","output",None,None),("cycle_complete","bool","output",None,None)]),
"rotary_barrel_tumbler":("machines.finishing.tumbler.rotary-barrel.v1","Rotary Barrel Mass-Finishing Tumbler","machines/finishing/tumblers",[2.9,2.0,1.8],[("barrel_rotation","continuous","KIN_ROTARY_BARREL",0,360,"deg",30)],[("run_command","bool","input",None,"barrel_rotation"),("speed_setpoint","float32","input","rpm",None),("running","bool","output",None,None),("cycle_complete","bool","output",None,None),("finisher_fault","bool","output",None,None)]),
"enclosed_laser_marking_station":("machines.marking.laser.enclosed-class1.v1","Enclosed Laser Marking Station","machines/marking/laser",[1.9,2.2,1.7],[("door_position","linear","KIN_SAFETY_DOOR",0,1.10,"m",.35),("head_z","linear","KIN_LASER_HEAD",0,.45,"m",.12)],[("mark_start","bool","input",None,None),("door_open","bool","input",None,"door_position"),("focus_position","float32","input","mm","head_z"),("door_closed","bool","output",None,None),("laser_ready","bool","output",None,None),("mark_complete","bool","output",None,None),("laser_fault","bool","output",None,None)]),
}
def axis(a):i,k,n,lo,hi,u,r=a;return {"id":i,"kind":k,"nodePath":n,"minimum":lo,"maximum":hi,"unit":u,"maximumRate":r}
def signal(s):i,t,d,u,k=s;return {"id":i,"dataType":t,"direction":d,"unit":u,"kinematicAxis":k,"description":i.replace('_',' ').capitalize()+"."}
def main():
    doc=json.loads(CATALOG.read_text(encoding="utf-8"));by={a["id"]:a for a in doc["assets"]}
    for slug,(aid,name,category,bounds,axes,signals) in SPECS.items():
        by[aid]={"id":aid,"displayName":name,"category":category,"tags":[name.lower(),slug.replace('_',' ')],"model":{"sourceBlend":f"res://assets/production-machines/{slug}/source/{slug}.blend","deliveryGltf":f"res://assets/production-machines/{slug}/delivery/{slug}.glb","lodFiles":[],"collisionFile":f"res://assets/production-machines/{slug}/collision/{slug}_collision.glb","thumbnailFile":f"res://assets/production-machines/{slug}/thumbnail.png"},"bounds":{"widthM":bounds[0],"heightM":bounds[1],"depthM":bounds[2]},"connectors":[],"kinematics":[axis(a) for a in axes],"signals":[signal(s) for s in signals],"quality":{"status":"candidate","blindReviewId":None,"recognitionConfidence":None,"topologyReviewed":True,"materialReviewed":True,"scaleReviewed":True,"animationReviewed":False}}
    ids=[v[0] for v in SPECS.values()];removed=set(ids)|{"machines.finishing.vibratory-bowl.batch.v1","machines.finishing.vibratory-tub.batch.v1"};base=[a for a in doc["assets"] if a["id"] not in removed];doc["assets"]=base+[by[i] for i in ids];CATALOG.write_text(json.dumps(doc,indent=2)+"\n",encoding="utf-8");print("REGISTERED_PRODUCTION_MACHINES",len(SPECS));print("TOTAL_CANDIDATES",len(doc["assets"]))
if __name__=="__main__":main()
