"""Register factory utility-system assets as catalog candidates."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];CATALOG=ROOT/"assets"/"catalog"/"candidates.catalog.json"
# slug: id, display name, category, bounds, axes, signals
SPECS={
"rotary_screw_air_compressor":("utilities.compressed-air.compressor.rotary-screw-enclosed.v1","Enclosed Rotary-Screw Air Compressor","utilities/compressed-air/compressors",[2.5,1.3,1.7],[],[("run_command","bool","input",None,None),("pressure_setpoint","float32","input","bar",None),("running","bool","output",None,None),("discharge_pressure","float32","output","bar",None),("compressor_fault","bool","output",None,None)]),
"vertical_air_receiver":("utilities.compressed-air.receiver.vertical.v1","Vertical Compressed-Air Receiver","utilities/compressed-air/receivers",[1.5,1.5,2.9],[],[("receiver_pressure","float32","output","bar",None),("high_pressure_alarm","bool","output",None,None),("drain_command","bool","input",None,None)]),
"refrigerated_air_dryer":("utilities.compressed-air.dryer.refrigerated.v1","Refrigerated Compressed-Air Dryer","utilities/compressed-air/dryers",[1.5,1.0,1.6],[],[("enable_command","bool","input",None,None),("dew_point","float32","output","degC",None),("dryer_fault","bool","output",None,None)]),
"twin_tower_desiccant_dryer":("utilities.compressed-air.dryer.desiccant-twin-tower.v1","Twin-Tower Desiccant Air Dryer","utilities/compressed-air/dryers",[1.9,1.1,2.5],[],[("enable_command","bool","input",None,None),("active_tower","int32","output",None,None),("dew_point","float32","output","degC",None),("dryer_fault","bool","output",None,None)]),
"air_cooled_water_chiller":("utilities.cooling.chiller.air-cooled-two-fan.v1","Two-Fan Air-Cooled Water Chiller","utilities/cooling/chillers",[2.9,1.6,1.8],[("fan_a_rotation","continuous","KIN_CONDENSER_FAN_-0.72_RING",0,360,"deg",1440),("fan_b_rotation","continuous","KIN_CONDENSER_FAN_0.72_RING",0,360,"deg",1440)],[("enable_command","bool","input",None,None),("leaving_water_setpoint","float32","input","degC",None),("leaving_water_temperature","float32","output","degC",None),("chiller_running","bool","output",None,None),("chiller_fault","bool","output",None,None)]),
"induced_draft_cooling_tower":("utilities.cooling.tower.induced-draft-package.v1","Package Induced-Draft Cooling Tower","utilities/cooling/towers",[2.4,1.9,2.8],[("fan_rotation","continuous","KIN_TOWER_FAN_RING",0,360,"deg",1080)],[("fan_command","bool","input",None,"fan_rotation"),("basin_temperature","float32","output","degC",None),("low_level_alarm","bool","output",None,None)]),
"horizontal_firetube_boiler":("utilities.steam.boiler.horizontal-firetube.v1","Horizontal Firetube Steam Boiler","utilities/steam/boilers",[3.8,1.8,2.8],[],[("enable_command","bool","input",None,None),("steam_pressure_setpoint","float32","input","bar",None),("steam_pressure","float32","output","bar",None),("flame_proven","bool","output",None,None),("boiler_trip","bool","output",None,None)]),
"rotary_vane_vacuum_pump":("utilities.vacuum.pump.oil-sealed-rotary-vane.v1","Oil-Sealed Rotary-Vane Vacuum Pump","utilities/vacuum/pumps",[2.0,1.0,1.3],[("motor_rotation","continuous","KIN_MOTOR_SHAFT",0,360,"deg",1800)],[("run_command","bool","input",None,"motor_rotation"),("vacuum_level","float32","output","kPa",None),("pump_fault","bool","output",None,None)]),
"regenerative_blower":("utilities.air.blower.regenerative-side-channel.v1","Regenerative Side-Channel Blower","utilities/air/blowers",[2.1,1.1,1.7],[("motor_rotation","continuous","KIN_MOTOR_SHAFT",0,360,"deg",3600)],[("run_command","bool","input",None,"motor_rotation"),("discharge_pressure","float32","output","kPa",None),("blower_fault","bool","output",None,None)]),
"hydraulic_power_unit":("utilities.hydraulic.power-unit.production-skid.v1","Production Hydraulic Power Unit","utilities/hydraulic/power-units",[2.3,1.4,1.9],[("pump_motor_rotation","continuous","KIN_PUMP_MOTOR",0,360,"deg",1800)],[("pump_command","bool","input",None,"pump_motor_rotation"),("pressure_setpoint","float32","input","bar",None),("system_pressure","float32","output","bar",None),("low_oil_level","bool","output",None,None),("hydraulic_fault","bool","output",None,None)]),
"central_lubrication_skid":("utilities.lubrication.centralized-grease-skid.v1","Centralized Grease Lubrication Skid","utilities/lubrication/systems",[1.8,1.1,2.0],[("pump_rotation","continuous","KIN_LUBE_PUMP",0,360,"deg",300)],[("lube_cycle_command","bool","input",None,"pump_rotation"),("cycle_complete","bool","output",None,None),("low_grease_level","bool","output",None,None),("lube_fault","bool","output",None,None)]),
"psa_nitrogen_generator":("utilities.gas-generation.nitrogen-psa-twin-tower.v1","Twin-Tower PSA Nitrogen Generator","utilities/gas-generation/nitrogen",[2.4,1.3,2.7],[],[("enable_command","bool","input",None,None),("nitrogen_purity","float32","output","percent",None),("active_tower","int32","output",None,None),("generator_fault","bool","output",None,None)]),
"plate_frame_heat_exchanger":("utilities.heat-transfer.plate-frame-gasketed.v1","Gasketed Plate-and-Frame Heat Exchanger","utilities/heat-transfer/exchangers",[1.8,1.1,1.9],[],[("primary_inlet_temperature","float32","input","degC",None),("secondary_inlet_temperature","float32","input","degC",None),("secondary_outlet_temperature","float32","output","degC",None)]),
"condensate_return_unit":("utilities.steam.condensate-return-duplex.v1","Duplex Steam Condensate Return Unit","utilities/steam/condensate",[2.6,1.4,2.0],[("pump_a_rotation","continuous","KIN_PUMP_0.62",0,360,"deg",1800),("pump_b_rotation","continuous","KIN_PUMP_0.98",0,360,"deg",1800)],[("auto_enable","bool","input",None,None),("receiver_level","float32","output","percent",None),("pump_a_running","bool","output",None,"pump_a_rotation"),("pump_b_running","bool","output",None,"pump_b_rotation"),("high_level_alarm","bool","output",None,None)]),
}
def axis(a):i,k,n,lo,hi,u,r=a;return {"id":i,"kind":k,"nodePath":n,"minimum":lo,"maximum":hi,"unit":u,"maximumRate":r}
def signal(s):i,t,d,u,k=s;return {"id":i,"dataType":t,"direction":d,"unit":u,"kinematicAxis":k,"description":i.replace('_',' ').capitalize()+"."}
def main():
    doc=json.loads(CATALOG.read_text(encoding="utf-8"));by={a["id"]:a for a in doc["assets"]}
    for slug,(aid,name,category,bounds,axes,signals) in SPECS.items():
        by[aid]={"id":aid,"displayName":name,"category":category,"tags":[name.lower(),slug.replace('_',' ')],"model":{"sourceBlend":f"res://assets/utilities/{slug}/source/{slug}.blend","deliveryGltf":f"res://assets/utilities/{slug}/delivery/{slug}.glb","lodFiles":[],"collisionFile":f"res://assets/utilities/{slug}/collision/{slug}_collision.glb","thumbnailFile":f"res://assets/utilities/{slug}/thumbnail.png"},"bounds":{"widthM":bounds[0],"heightM":bounds[1],"depthM":bounds[2]},"connectors":[],"kinematics":[axis(a) for a in axes],"signals":[signal(s) for s in signals],"quality":{"status":"candidate","blindReviewId":None,"recognitionConfidence":None,"topologyReviewed":True,"materialReviewed":True,"scaleReviewed":True,"animationReviewed":False}}
    ids=[v[0] for v in SPECS.values()];base=[a for a in doc["assets"] if a["id"] not in set(ids)];doc["assets"]=base+[by[i] for i in ids];CATALOG.write_text(json.dumps(doc,indent=2)+"\n",encoding="utf-8");print("REGISTERED_UTILITIES",len(SPECS));print("TOTAL_CANDIDATES",len(doc["assets"]))
if __name__=="__main__":main()
