"""Register material-flow tranche as candidate-only catalog assets."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];CATALOG=ROOT/"assets"/"catalog"/"candidates.catalog.json"

# slug: id, name, category, bounds, axes, signals
SPECS={
"gravity_roller_conveyor":("material-handling.conveyor.gravity-roller-800x2400.v1","Gravity Roller Conveyor Section","material-handling/conveyors/roller",[2.5,1.45,.90],[],[]),
"pallet_chain_conveyor":("material-handling.conveyor.pallet-chain-2strand.v1","Two-Strand Pallet Chain Conveyor","material-handling/conveyors/chain",[3.0,1.30,1.25],[('chain_speed','linear_continuous','KIN_CHAIN_SLAT_-0.31_0',-1.0,1.0,'m/s',.8)],[('run_command','bool','input',None,'chain_speed'),('speed_setpoint','float32','input','m/s','chain_speed'),('actual_speed','float32','output','m/s','chain_speed'),('running','bool','output',None,None)]),
"steel_slat_conveyor":("material-handling.conveyor.steel-slat.v1","Steel Slat Conveyor","material-handling/conveyors/slat",[2.8,1.35,1.25],[('slat_speed','linear_continuous','KIN_SLAT_0',-1.2,1.2,'m/s',1.0)],[('run_command','bool','input',None,'slat_speed'),('speed_setpoint','float32','input','m/s','slat_speed'),('actual_speed','float32','output','m/s','slat_speed'),('running','bool','output',None,None)]),
"modular_plastic_belt_conveyor":("material-handling.conveyor.modular-plastic-belt.v1","Modular Plastic Belt Conveyor","material-handling/conveyors/belt",[2.8,1.35,1.30],[('belt_speed','linear_continuous','KIN_BELT_LINK_0_0',-1.5,1.5,'m/s',1.2)],[('run_command','bool','input',None,'belt_speed'),('speed_setpoint','float32','input','m/s','belt_speed'),('actual_speed','float32','output','m/s','belt_speed'),('running','bool','output',None,None)]),
"popup_chain_transfer":("material-handling.transfer.popup-chain-90deg.v1","90-Degree Pop-Up Chain Transfer","material-handling/transfers",[2.4,1.35,1.25],[('transfer_lift','linear','KIN_LIFT_CYLINDER',0,.12,'m',.4),('chain_speed','linear_continuous','KIN_POPUP_CHAIN_-0.28',-1,1,'m/s',.8)],[('raise_command','bool','input',None,'transfer_lift'),('run_command','bool','input',None,'chain_speed'),('raised','bool','output',None,None),('lowered','bool','output',None,None),('running','bool','output',None,None)]),
"vertical_reciprocating_conveyor":("material-handling.lift.vertical-reciprocating.v1","Vertical Reciprocating Conveyor","material-handling/lifts",[1.55,1.25,2.85],[('carriage_height','linear','KIN_LIFT_CARRIAGE',0,1.35,'m',.65)],[('raise_command','bool','input',None,'carriage_height'),('lower_command','bool','input',None,'carriage_height'),('height_m','float32','output','m','carriage_height'),('upper_limit','bool','output',None,None),('lower_limit','bool','output',None,None)]),
"open_trough_screw_conveyor":("material-handling.conveyor.screw-open-trough.v1","Open-Trough Screw Conveyor","material-handling/bulk/screw-conveyors",[3.2,1.05,1.55],[('screw_speed','angular_continuous','KIN_SCREW_SHAFT',-180,180,'rpm',300)],[('run_command','bool','input',None,'screw_speed'),('speed_setpoint_rpm','float32','input','rpm','screw_speed'),('actual_speed_rpm','float32','output','rpm','screw_speed'),('running','bool','output',None,None)]),
"bucket_elevator":("material-handling.elevator.bucket-continuous.v1","Continuous Bucket Elevator","material-handling/bulk/elevators",[2.0,1.45,2.95],[('bucket_speed','linear_continuous','KIN_BUCKET_BELT',0,1.5,'m/s',.8)],[('run_command','bool','input',None,'bucket_speed'),('speed_setpoint','float32','input','m/s','bucket_speed'),('actual_speed','float32','output','m/s','bucket_speed'),('running','bool','output',None,None)]),
"vibratory_bowl_feeder":("material-handling.feeder.vibratory-bowl.v1","Vibratory Bowl Feeder","material-handling/feeders/vibratory",[1.65,1.45,1.35],[('feed_rate','linear_continuous','KIN_SPIRAL_TRACK_0',0,1,'normalized',2.0)],[('run_command','bool','input',None,'feed_rate'),('amplitude_setpoint','float32','input','percent','feed_rate'),('part_available','bool','output',None,None),('running','bool','output',None,None)]),
"bulk_hopper_slide_gate":("material-handling.hopper.bulk-slide-gate.v1","Bulk Hopper with Powered Slide Gate","material-handling/bulk/hoppers",[1.75,1.45,2.05],[('gate_position','linear','KIN_SLIDE_GATE',0,.40,'m',.35)],[('open_command','bool','input',None,'gate_position'),('close_command','bool','input',None,'gate_position'),('gate_open','bool','output',None,None),('gate_closed','bool','output',None,None)]),
"powered_diverter_arm":("material-handling.diverter.powered-swing-arm.v1","Powered Conveyor Swing-Arm Diverter","material-handling/diverters",[2.5,1.25,1.45],[('diverter_angle','angular','KIN_DIVERTER_ARM',0,35,'deg',90)],[('divert_command','bool','input',None,'diverter_angle'),('home_command','bool','input',None,'diverter_angle'),('diverted','bool','output',None,None),('home','bool','output',None,None)]),
"pneumatic_pallet_stop":("material-handling.stop.pneumatic-pallet.v1","Pneumatic Pallet Stop","material-handling/stops",[.95,.72,1.10],[('stop_height','linear','KIN_STOP_BLADE',0,.30,'m',.5)],[('raise_command','bool','input',None,'stop_height'),('lower_command','bool','input',None,'stop_height'),('raised','bool','output',None,None),('lowered','bool','output',None,None),('pallet_present','bool','output',None,None)]),
}
def axis(a):
    i,k,n,lo,hi,u,r=a;return {"id":i,"kind":k,"nodePath":n,"minimum":lo,"maximum":hi,"unit":u,"maximumRate":r}
def signal(s):
    i,t,d,u,k=s;return {"id":i,"dataType":t,"direction":d,"unit":u,"kinematicAxis":k,"description":i.replace('_',' ').capitalize()+"."}
def main():
    doc=json.loads(CATALOG.read_text(encoding="utf-8"));by={a["id"]:a for a in doc["assets"]}
    for slug,(aid,name,category,bounds,axes,signals) in SPECS.items():
        by[aid]={"id":aid,"displayName":name,"category":category,"tags":[name.lower(),slug.replace('_',' ')],"model":{"sourceBlend":f"res://assets/material_flow/{slug}/source/{slug}.blend","deliveryGltf":f"res://assets/material_flow/{slug}/delivery/{slug}.glb","lodFiles":[],"collisionFile":f"res://assets/material_flow/{slug}/collision/{slug}_collision.glb","thumbnailFile":f"res://assets/material_flow/{slug}/thumbnail.png"},"bounds":{"widthM":bounds[0],"heightM":bounds[1],"depthM":bounds[2]},"connectors":[],"kinematics":[axis(a) for a in axes],"signals":[signal(s) for s in signals],"quality":{"status":"candidate","blindReviewId":None,"recognitionConfidence":None,"topologyReviewed":True,"materialReviewed":True,"scaleReviewed":True,"animationReviewed":False}}
    ids=[v[0] for v in SPECS.values()];base=[a for a in doc["assets"] if a["id"] not in set(ids)];doc["assets"]=base+[by[i] for i in ids];CATALOG.write_text(json.dumps(doc,indent=2)+"\n",encoding="utf-8");print("REGISTERED_MATERIAL_FLOW",len(SPECS));print("TOTAL_CANDIDATES",len(doc["assets"]))
if __name__=="__main__":main()
