"""Register process-fluid tranche as candidate-only catalog assets."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];CATALOG=ROOT/"assets"/"catalog"/"candidates.catalog.json"

# slug: id, display name, category, bounds, fluid ports, axes, signals
SPECS={
"flanged_gate_valve":("process.valve.gate.flanged-handwheel.v1","Flanged Rising-Stem Gate Valve","process/valves/isolation",[2.4,.9,2.35],[(-1.15,0,.75),(1.15,0,.75)],[('stem_position','linear','KIN_STEM',0,.34,'m',.12),('handwheel_angle','angular_continuous','KIN_HANDWHEEL',-3600,3600,'deg',360)],[('open_command','bool','input',None,'stem_position'),('close_command','bool','input',None,'stem_position'),('position_percent','float32','output','percent','stem_position'),('open_limit','bool','output',None,None),('closed_limit','bool','output',None,None)]),
"flanged_globe_valve":("process.valve.globe.flanged-handwheel.v1","Flanged Globe Valve","process/valves/throttling",[2.4,1.0,2.25],[(-1.15,0,.75),(1.15,0,.75)],[('stem_position','linear','KIN_STEM',0,.18,'m',.08),('handwheel_angle','angular_continuous','KIN_HANDWHEEL',-1800,1800,'deg',300)],[('position_command','float32','input','percent','stem_position'),('position_percent','float32','output','percent','stem_position')]),
"wafer_butterfly_valve":("process.valve.butterfly.wafer-lever.v1","Wafer Butterfly Valve with Lever","process/valves/isolation",[2.3,1.0,1.75],[(-1.08,0,.75),(1.08,0,.75)],[('disc_angle','angular','KIN_DISC',0,90,'deg',90),('lever_angle','angular','KIN_LEVER',0,90,'deg',90)],[('open_command','bool','input',None,'disc_angle'),('close_command','bool','input',None,'disc_angle'),('position_percent','float32','output','percent','disc_angle')]),
"swing_check_valve":("process.valve.check.swing-flanged.v1","Flanged Swing Check Valve","process/valves/check",[2.4,1.1,1.65],[(-1.15,0,.75),(1.15,0,.75)],[],[('flow_present','bool','output',None,None)]),
"knife_gate_valve":("process.valve.knife-gate.handwheel.v1","Handwheel Knife-Gate Valve","process/valves/slurry",[2.3,1.0,2.65],[(-1.08,0,.72),(1.08,0,.72)],[('blade_position','linear','KIN_GATE_BLADE',0,.70,'m',.16),('handwheel_angle','angular_continuous','KIN_HANDWHEEL',-3600,3600,'deg',360)],[('open_command','bool','input',None,'blade_position'),('close_command','bool','input',None,'blade_position'),('position_percent','float32','output','percent','blade_position')]),
"pneumatic_control_valve":("process.valve.control.globe-diaphragm.v1","Pneumatic Globe Control Valve","process/valves/control",[2.4,1.15,2.35],[(-1.15,0,.75),(1.15,0,.75)],[('stem_position','linear','KIN_STEM',0,.14,'m',.10)],[('position_command','float32','input','percent','stem_position'),('position_feedback','float32','output','percent','stem_position'),('air_failure','bool','input',None,None)]),
"end_suction_centrifugal_pump":("process.pump.centrifugal.end-suction-baseplate.v1","Baseplate End-Suction Centrifugal Pump","process/pumps/centrifugal",[2.4,1.1,1.45],[(1.25,0,.52),(.48,0,1.30)],[('shaft_speed','angular_continuous','COUPLING_GUARD',-3600,3600,'rpm',1800)],[('run_command','bool','input',None,'shaft_speed'),('speed_setpoint_rpm','float32','input','rpm','shaft_speed'),('running','bool','output',None,None),('discharge_pressure','float32','output','bar',None)]),
"air_operated_double_diaphragm_pump":("process.pump.aodd.dual-diaphragm.v1","Air-Operated Double-Diaphragm Pump","process/pumps/positive-displacement",[1.5,1.05,1.35],[(0,-.50,.26),(0,.50,1.08)],[],[('air_enable','bool','input',None,None),('stroke_rate','float32','input','cycles/min',None),('running','bool','output',None,None),('leak_alarm','bool','output',None,None)]),
"external_gear_pump":("training.hydraulics.power-unit.external-gear-cutaway.v1","External-Gear Hydraulic Power Unit Trainer","training/hydraulics/power-units",[2.8,2.2,1.65],[(-1.23,.18,.36),(.68,.10,.92)],[('shaft_speed','angular_continuous','KIN_PUMP_SHAFT',-3000,3000,'rpm',1500)],[('run_command','bool','input',None,'shaft_speed'),('speed_setpoint_rpm','float32','input','rpm','shaft_speed'),('running','bool','output',None,None),('system_pressure','float32','output','bar',None)]),
"filter_regulator_lubricator":("pneumatics.air-preparation.frl-three-piece.v1","Three-Piece Filter-Regulator-Lubricator","pneumatics/air-preparation",[1.6,.85,1.55],[(-.72,0,1.02),(.72,0,1.02)],[('pressure_setting','angular_continuous','KIN_PRESSURE_KNOB',0,1080,'deg',180)],[('pressure_setpoint','float32','input','bar','pressure_setting'),('outlet_pressure','float32','output','bar','pressure_setting'),('filter_dp_alarm','bool','output',None,None)]),
"pneumatic_valve_manifold":("pneumatics.valve-manifold.seven-station.v1","Seven-Station Pneumatic Solenoid Valve Manifold","pneumatics/directional-control",[2.2,.85,1.05],[(-1.18,0,.48)],[],[('valve_1_command','bool','input',None,None),('valve_2_command','bool','input',None,None),('valve_3_command','bool','input',None,None),('supply_pressure_ok','bool','output',None,None)]),
"shell_tube_heat_exchanger":("process.heat-exchanger.shell-tube-horizontal.v1","Horizontal Shell-and-Tube Heat Exchanger","process/heat-transfer",[3.7,1.25,1.85],[(-1.70,0,1.0),(1.70,0,1.0),(-.70,0,1.72),(.70,0,.28)],[],[('shell_inlet_temperature','float32','input','degC',None),('tube_inlet_temperature','float32','input','degC',None),('shell_outlet_temperature','float32','output','degC',None),('tube_outlet_temperature','float32','output','degC',None)]),
"cyclone_separator":("process.separator.cyclone-tangential.v1","Tangential-Inlet Cyclone Separator","process/separation/dust",[2.2,1.8,3.45],[(-1.15,-.34,2.02),(0,0,2.82),(0,0,-.55)],[],[('airflow','float32','input','m3/h',None),('dust_level_high','bool','output',None,None),('differential_pressure','float32','output','Pa',None)]),
"pulse_jet_dust_collector":("process.filter.dust-collector.pulse-jet.v1","Pulse-Jet Dust Collector","process/separation/dust",[2.6,1.5,3.3],[(-1.30,0,1.35),(1.38,0,2.68),(0,0,-.12)],[],[('fan_run_command','bool','input',None,None),('pulse_enable','bool','input',None,None),('differential_pressure','float32','output','Pa',None),('hopper_level_high','bool','output',None,None)]),
}

def axis(a):
    i,k,n,lo,hi,u,r=a;return {"id":i,"kind":k,"nodePath":n,"minimum":lo,"maximum":hi,"unit":u,"maximumRate":r}
def signal(s):
    i,t,d,u,k=s;return {"id":i,"dataType":t,"direction":d,"unit":u,"kinematicAxis":k,"description":i.replace('_',' ').capitalize()+"."}
def connector(i,p,opposed=False):
    return {"id":f"process_{i}","kind":"process_fluid","positionM":list(p),"rotationDeg":[0,180 if opposed else 0,0],"compatibleKinds":["process_fluid"]}
def main():
    doc=json.loads(CATALOG.read_text(encoding="utf-8"));by={a["id"]:a for a in doc["assets"]}
    for slug,(aid,name,category,bounds,ports,axes,signals) in SPECS.items():
        by[aid]={"id":aid,"displayName":name,"category":category,"tags":[name.lower(),slug.replace('_',' ')],"model":{"sourceBlend":f"res://assets/process_fluid/{slug}/source/{slug}.blend","deliveryGltf":f"res://assets/process_fluid/{slug}/delivery/{slug}.glb","lodFiles":[],"collisionFile":f"res://assets/process_fluid/{slug}/collision/{slug}_collision.glb","thumbnailFile":f"res://assets/process_fluid/{slug}/thumbnail.png"},"bounds":{"widthM":bounds[0],"heightM":bounds[1],"depthM":bounds[2]},"connectors":[connector(i,p,i%2==1) for i,p in enumerate(ports,1)],"kinematics":[axis(a) for a in axes],"signals":[signal(s) for s in signals],"quality":{"status":"candidate","blindReviewId":None,"recognitionConfidence":None,"topologyReviewed":True,"materialReviewed":True,"scaleReviewed":True,"animationReviewed":False}}
    ids=[v[0] for v in SPECS.values()];retired={"process.filter.baghouse.pulse-jet.v1","process.filter.dust-collector.pulse-jet-cartridge.v1","process.pump.gear.external-baseplate.v1","process.pump.gear.external-cutaway.v1","process.pump.gear.external-sae-flange.v1","process.pump.gear.external-motor-skid.v1"};base=[a for a in doc["assets"] if a["id"] not in set(ids)|retired];doc["assets"]=base+[by[i] for i in ids];CATALOG.write_text(json.dumps(doc,indent=2)+"\n",encoding="utf-8");print("REGISTERED_PROCESS_FLUID",len(SPECS));print("TOTAL_CANDIDATES",len(doc["assets"]))
if __name__=="__main__":main()
